parameters = {
    'A01': {'name': "Crop and animal production, hunting and related service activities", 'value': 0},
    'A02': {'name': "Forestry and logging", 'value': 0},
    'A03': {'name': "Fishing and aquaculture", 'value': 0},
    'B': {'name': "Mining and quarrying", 'value': 0},
    'C10_12': {'name': "Manufacture of food products, beverages and tobacco products", 'value': 0},
    'C13_15': {'name': "Manufacture of textiles, wearing apparel and leather products", 'value': 0},
    'C16': {'name': "Manufacture of wood and of products of wood and cork, except furniture; manufacture of articles "
                    "of straw and plaiting materials", 'value': 0},
    'C17': {'name': "Manufacture of paper and paper products", 'value': 0},
    'C18': {'name': "Printing and reproduction of recorded media", 'value': 0},
    'C19': {'name': "Manufacture of coke and refined petroleum products ", 'value': 0},
    'C20': {'name': "Manufacture of chemicals and chemical products", 'value': 0},
    'C21': {'name': "Manufacture of basic pharmaceutical products and pharmaceutical preparations", 'value': 0},
    'C22': {'name': "Manufacture of rubber and plastic products", 'value': 0},
    'C23': {'name': "Manufacture of other non-metallic mineral products", 'value': 0},
    'C24': {'name': "Manufacture of basic metals", 'value': 0},
    'C25': {'name': "Manufacture of fabricated metal products, except machinery and equipment", 'value': 0},
    'C26': {'name': "Manufacture of computer, electronic and optical products", 'value': 0},
    'C27': {'name': "Manufacture of electrical equipment", 'value': 0},
    'C28': {'name': "Manufacture of machinery and equipment n.e.c.", 'value': 0},
    'C29': {'name': "Manufacture of motor vehicles, trailers and semi-trailers", 'value': 0},
    'C30': {'name': "Manufacture of other transport equipment", 'value': 0},
    'C31_32': {'name': "Manufacture of furniture; other manufacturing", 'value': 0},
    'C33': {'name': "Repair and installation of machinery and equipment", 'value': 0},
    'D': {'name': "Electricity, gas, steam and air conditioning supply", 'value': 0},
    'E36': {'name': "Water collection, treatment and supply", 'value': 0},
    'E37_39': {'name': "Sewerage; waste collection, treatment and disposal activities; materials recovery; remediation "
                       "activities and other waste management services ", 'value': 0},
    'F': {'name': "Construction", 'value': 0},
    'G45': {'name': "Wholesale and retail trade and repair of motor vehicles and motorcycles", 'value': 0},
    'G46': {'name': "Wholesale trade, except of motor vehicles and motorcycles", 'value': 0},
    'G47': {'name': "Retail trade, except of motor vehicles and motorcycles", 'value': 0},
    'H49': {'name': "Land transport and transport via pipelines", 'value': 0},
    'H50': {'name': "Water transport", 'value': 0},
    'H51': {'name': "Air transport", 'value': 0},
    'H52': {'name': "Warehousing and support activities for transportation", 'value': 0},
    'H53': {'name': "Postal and courier activities", 'value': 0},
    'I': {'name': "Accommodation and food service activities", 'value': 0},
    'J58': {'name': "Publishing activities", 'value': 0},
    'J59_60': {'name': "Motion picture, video and television programme production, sound recording and music "
                       "publishing activities; programming and broadcasting activities", 'value': 0},
    'J61': {'name': "Telecommu-nications", 'value': 0},
    'J62_63': {'name': "Computer programming, consultancy and related activities; information service activities",
               'value': 0},
    'K64': {'name': "Financial service activities, except insurance and pension funding", 'value': 0},
    'K65': {'name': "Insurance, reinsurance and pension funding, except compulsory social security", 'value': 0},
    'K66': {'name': "Activities auxiliary to financial services and insurance activities", 'value': 0},
    'L68': {'name': "Real estate activities without imputed rents", 'value': 0},
    'M69_70': {'name': "Legal and accounting activities; activities of head offices; management consultancy activities",
               'value': 0},
    'M71': {'name': "Architectural and engineering activities; technical testing and analysis", 'value': 0},
    'M72': {'name': "Scientific research and development", 'value': 0},
    'M73': {'name': "Advertising and market research", 'value': 0},
    'M74_75': {'name': "Other professional, scientific and technical activities; veterinary activities", 'value': 0},
    'N77': {'name': "Rental and leasing activities", 'value': 0},
    'N78': {'name': "Employment activities", 'value': 0},
    'N79': {'name': "Travel agency, tour operator reservation service and related activities", 'value': 0},
    'N80_82': {'name': "Security and investigation activities; services to buildings and landscape activities; office "
                       "administrative, office support and other business support activities", 'value': 0},
    'O': {'name': "Public administration and defence; compulsory social security", 'value': 0},
    'P': {'name': "Education", 'value': 0},
    'Q86': {'name': "Human health activities", 'value': 0},
    'Q87_88': {'name': "Social work activities", 'value': 0},
    'R90_92': {'name': "Creative, arts and entertainment activities; libraries, archives, museums and other cultural "
                       "activities; gambling and betting activities", 'value': 0},
    'R93': {'name': "Sports activities and amusement and recreation activities", 'value': 0},
    'S94': {'name': "Activities of membership organisations", 'value': 0},
    'S95': {'name': "Repair of computers and personal and household goods", 'value': 0},
    'S96': {'name': "Other personal service activities", 'value': 0},
    'T': {'name': "Activities of households as employers; undifferentiated goods- and services-producing activities of "
                  "households for own use", 'value': 0},
    'U': {'name': "Activities of extra-territorial organisations and bodies", 'value': 0}
}

output_parameters = {
    1: {'id': 'RCS', 'name': 'Regional Capital Stock'},
    2: {'id': 'RTPO', 'name': 'Regional Total Production Output'},
    3: {'id': 'RPSE', 'name': 'Regional Paid Staff Expenses'},
    4: {'id': 'RE', 'name': 'Regional Employment'},
    5: {'id': 'RPP', 'name': 'Regional Product Prices'},
    6: {'id': 'RDfI', 'name': 'Regional Demand for Investments'},
    7: {'id': 'RAC', 'name': 'Regional Aggregate Consumption'},
    8: {'id': 'RDI', 'name': 'Regional Disposable Income'},
    9: {'id': 'RDP', 'name': 'Regional Gross Domestic Product'},
    10: {'id': 'HP', 'name': 'House Prices'},
}
